name: Self Hosted Python CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Create virtual environment
      run: |
        python3 -m venv venv

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        source venv/bin/activate
        cd src
        pytest addition.py
